### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by nhadler** [Novartis/UNIQUE#2]
Hi, will the documentation be built and hosted soon? I'm interested in applying this package, but it's a bit hard to understand parsing the raw documentation.

**Comment by gscebba** [comment]
Hi @nhadler and thank you for your interest in using the package! Yes, we are currently working on the documentation. It will be up soon.

**Comment by gscebba** [comment]
Here you go! https://opensource.nibr.com/UNIQUE
